apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
  namespace: agents
  labels:
    app: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register-container
        image: vcf-np-w2-harbor-az1.sunat.peru/agentes/register:latest
        ports:
        - containerPort: 8501
        env:
        # - name: AGENT_URL
        #   value: "http://fastapi-service.default.svc.cluster.local"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5002"
          # value: "http://mlflow.agents.svc.cluster.local:5002"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
          # value: "http://minio.agents.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minio123"
        - name: OPENAI_API_KEY
          value: "Ignored"
        - name: OPENAI_API_BASE_URLS
          value: "http://ollama-service:11434/v1"
        - name: CHECKER_LLM_NAME
          value: "llama3.2:3b"
        - name: IMPROVER_LLM_NAME
          value: "llama3.2:3b"
        - name: RAG_LLM_NAME
          value: "llama3.2:3b"
---
apiVersion: v1
kind: Service
metadata:
  name: register
  namespace: agents
spec:
  selector:
    app: register
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
