apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-claim-agents
  namespace: agents
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
