apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim-agents
  namespace: agents
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
