apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-agents
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /bitnami/postgresql/agents
